### ISSUE TITLE
Using the Apache Arrow C Data Interface

### ISSUE THREAD

**Issue by sterlinm** [mcaceresb/stata-parquet#20]
This project probably isn't active anymore, so hopefully this isn't a bother!

I was looking into seeing if anybody had used Apache Arrow to integrate Stata with Python and came across this project. I was curious if you'd looked into using Arrow to send data back and forth to Stata and other processes (Python, R, etc) without actually writing to disk. Apache Arrow [introduced](https://arrow.apache.org/blog/2020/05/03/introducing-arrow-c-data-interface/) a [C Data Interface](https://arrow.apache.org/docs/format/CDataInterface.html#) last year, and I was wondering if it would be possible to write a plugin for Stata that could move an Arrow table directly into memory without even needing to create a parquet file.

I know it's slightly different from this project, but was hoping it might be possible to make use of some of the work you've already done here. Feel free to ignore if it's no longer a topic of interest to you!

**Comment by mcaceresb** [comment]
This project is on hiatus largely because I started grad school so I haven't had much spare time in two years. I'm keen to do another pass at some point.

That said, moving data from Stata to python can be done from Stata 16 onward using the `python` command. As for a generic way of writing data into memory directly into disk, ny understanding was that is not technically feasible without some serious wrangling. I haven't looked into it in much depth so I could be off, tho.

**Comment by sterlinm** [comment]
Thanks!
